name: enough_mail_flutter
description: Widgets for email apps that use the `enough_mail` library. Licensed commercially friendly under MPL 2.0.
version: 2.1.1
homepage: https://github.com/enough-software/enough_mail_flutter
topics:
 - mime
 - email

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  enough_mail: ^2.1.2
  enough_mail_html: ^2.0.1
  enough_media: ^2.3.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  logger: ^2.0.0
  url_launcher: ^6.0.0

dependency_overrides:
  # xml: ^6.0.1
  # out-comment the following to enable local development:
  # enough_mail:
  #   path: ../enough_mail
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail.git
  # enough_mail_html:
  #   path: ../enough_mail_html
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail_html.git
  # enough_media:
  #   git:
  #     url: https://github.com/Enough-Software/enough_media.git
  #   path: ../enough_media



dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
# no assets or fonts used in this package